networks:
  pa_network:
    external: true

services:
  pa_website:
    container_name: pa_website
    build:
      context: ./WEBSITE
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - pa_api
    networks:
      - pa_network

  pa_api:
    container_name: pa_api
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - pa_db 
    networks:
      - pa_network

  pa_db:
    container_name: pa_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: pa2024
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./pa_storage:/var/lib/mysql
    networks:
      - pa_network

  notifs:
    container_name: pa_api
    build:
      context: ./NOTIFS-SERVER
      dockerfile: Dockerfile
    depends_on:
      - pa_api
    networks:
      - pa_network